---
- name: Install Applications for Debian 
  vars:
    os: "{{ansible_os_family|lower}}"
  block:
  - name: oh-my-zsh
    include: "{{os}}/oh_my_zsh.yml"
    when: "{{ applications.oh_my_zsh }}"

  - name: Google Chrome
    include: "{{os}}/chrome.yml"
    when: "{{applications.chrome}}"

  - name: Docker
    include: "{{os}}/goland.yml"
    when: "{{applications.docker}}"
  
  - name: Golang
    include: "{{os}}/golang.yml"
    when: "{{applications.golang.install}}"
  
  - name: Goland
    include: "{{os}}/goland.yml"
    when: "{{applications.goland}}"
    
  - name: Postman
    include: "{{os}}/postman.yml"
    when: "{{applications.postman}}"
  
  - name: Spotify
    include: "{{os}}/spotify.yml"
    when: "{{applications.spotify}}"

  - name: VS-Code
    include: "{{os}}/vscode.yml"
    when: "{{applications.vscode}}"