---
- name: Install Applications for Debian 
  vars:
    os: "{{ansible_os_family|lower}}"
  block:
  - name: oh-my-zsh
    include: "{{os}}/oh_my_zsh.yml"
    when: "{{ application.oh_my_zsh }}"

  - name: Google Chrome
    include: "{{os}}/chrome.yml"
    when: "{{application.chrome}}"

  - name: Docker
    include: "{{os}}/goland.yml"
    when: "{{application.goland}}"
  
  - name: Golang
    include: "{{os}}/golang.yml"
    when: "{{application.golang}}"
  
  - name: Goland
    include: "{{os}}/goland.yml"
    when: "{{application.goland}}"
       