---
- name: Playbook to manage aferen dotfiles
  hosts: localhost
  connection: local
  vars:
    os: "{{ansible_os_family|lower}}"
  tasks:
    - name: load custom vars
      include_vars: "{{os}}/variables.yml"
      tags:
        - always

    - name: Create folder
      file:
        path: "{{item}}"
        state: directory
      with_list: "{{folders}}"  

    - name: Generate ssh key
      command : ssh-keygen -q -t rsa -f "{{ lookup('env','HOME') }}/.ssh/id_rsa" -C "" -N ""
      args:
        creates: "{{ lookup('env','HOME') }}/.ssh/id_rsa"

    - include: "{{os}}/packages.yml"
      tags:
        - packages

    - include: "{{os}}/applications.yml"
      tags:
        - applications