---
- name: Playbook to manage aferen dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: variable.yml
      tags:
        - always

    - name: Create folder
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "~/.config/terminator/"
        - "~/.config/vscode/"
        - "~/.local/share/zsh/"
        - "~/workspace/"

    - include: packages.yml
      tags:
        - packages

    - include: applications.yml
      tags:
        - applications