---
- name: Playbook to manage aferen dotfiles
  hosts: localhost
  connection: local
  vars:
    os: "{{ansible_os_family|lower}}"
  tasks:
    - name: load custom vars
      include_vars: "{{os}}/variables.yml"
      tags:
        - always

    - name: Create folder
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "./temp"
        - "~/.config/vscode/"
        - "~/.local/share/zsh/"
        - "~/workspace/"

    - include: "{{os}}/packages.yml"
      tags:
        - packages

    - include: "{{os}}/applications.yml"
      tags:
        - applications